### PR TITLE
Add references

### PR DESCRIPTION
**Pull request by alexfoias**
Fixes https://github.com/courtois-neuromod/anat-processing-book/issues/12

### CODE REVIEW

**Comment by alexfoias** [comment]
@jcohenadad or @zelenkastiot could you please activate the CI build for sphinx so that I can see if my changes work ? thanks

**Comment by jcohenadad** [comment]
> @jcohenadad or @zelenkastiot could you please activate the CI build for sphinx so that I can see if my changes work ? thanks

the build is unfortunately _much more_ complicated than a regular RTD. @zelenkastiot has to build and push. We absolutely need to change this modus operandi. See https://github.com/courtois-neuromod/anat-processing-book/issues/15

**Comment by alexfoias** [comment]
@agahkarakuzu can I trigger a build from a fork ? thanks

**Comment by alexfoias** [comment]
Tested the current implementation and it works in local .

Here are some images:
**Introduction**
Screen Shot 2021-08-05 at 3 56 29 PM
**Bibliography**
Screen Shot 2021-08-05 at 3 56 39 PM

**Comment by agahkarakuzu** [comment]
@alexfoias you'll need to enable actions (there'll be a green button under actions tab) then add a personal access token with repo access as a secret. After that, it should work. Name of the token is in .github/workflows/main.yml.

**Comment by alexfoias** [comment]
@agahkarakuzu or @mathieuboudreau not sure how to setup the personal access token. Do you guys have some information on how to do it ? thanks.

**Comment by agahkarakuzu** [comment]
@alexfoias I solved that problem. The page is being deployed (with jupyter book build) automatically, you can see the actions run: 

https://github.com/courtois-neuromod/anat-processing-book/actions

**Comment by alexfoias** [comment]
@agahkarakuzu I have marked the PR as ready for review, but it doesn't seem to appear in the actions. Do I have to do something else ?

**Comment by alexfoias** [comment]
@mathieuboudreau Since I didn't have an answer to [my previous comment](https://github.com/courtois-neuromod/anat-processing-book/pull/36#issuecomment-918419938) do you think you could please help me ? thanks

**Comment by mathieuboudreau** [comment]
Stale PR that has been resolved in #49

**Pull request closed without merging**
